services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501" # Map to Traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`sentiment.taufiqdp.com`)" # Replace with your domain
      - "traefik.http.routers.whoami.entrypoints=web"

  traefik:
    image: "traefik:v3.2.1"
    command:
      - "--api.insecure=true" # Enables Traefik dashboard (optional; remove for production)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80" # Default HTTP port
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
